// Generated by train_export_forecast.py (fallback / convenience loader)
// If forecast.json exists, index.html can fetch it directly.
// This file is optional; keep it empty/unused unless you want to embed data.

